Repository nish-kishore/tidypolis, pull requests merged in 2024-02, with the labels that each got.

#17 #7 Update change logs
  R/init.R
  R/utils.R
Labels: enhancement

#26 closes #25
  R/utils.R
Labels: bug

#20 6 posit integration
  R/dal.R
  R/init.R
  R/utils.R
  renv.lock
Labels: documentation, enhancement

#28 Pre production evaluation
  DESCRIPTION
  NAMESPACE
  R/dal.R
  R/globals.R
  R/init.R
  R/utils.R
  README.md
  man/archive_log.Rd
  man/f.compare.metadata.Rd
  man/get_crosswalk_data.Rd
  man/get_polis_data.Rd
  man/init_tidypolis.Rd
  man/log_report.Rd
  man/preprocess_cdc.Rd
  man/tidypolis_io.Rd
  man/update_polis_log.Rd
  man/upload_cdc_proc_to_edav.Rd
  renv.lock
Labels: documentation, enhancement

#29 Release V1.0.0
  DESCRIPTION
  NAMESPACE
  R/dal.R
  R/globals.R
  R/init.R
  R/utils.R
  README.md
  man/archive_log.Rd
  man/f.compare.metadata.Rd
  man/get_crosswalk_data.Rd
  man/get_polis_data.Rd
  man/init_tidypolis.Rd
  man/log_report.Rd
  man/preprocess_cdc.Rd
  man/tidypolis_io.Rd
  man/update_polis_log.Rd
  man/upload_cdc_proc_to_edav.Rd
  renv.lock
Labels: enhancement
