Repository nish-kishore/tidypolis, pull requests merged in 2025-04, with the labels that each got.

#172 ❇️ Modularization of Preprocessing Step 1
  DESCRIPTION
  NAMESPACE
  R/utils.R
  man/archive_old_files.Rd
  man/clean_activity_table.Rd
  man/clean_case_table.Rd
  man/clean_es_table.Rd
  man/clean_subactivity_table.Rd
  man/clean_virus_table.Rd
  man/create_change_log.Rd
  man/create_core_ready_dir.Rd
  man/export_final_core_ready_files.Rd
  man/get_most_recent_files.Rd
  man/preprocess_cdc.Rd
  man/request_input.Rd
  man/tidypolis_io.Rd
  man/upload_cdc_proc_to_edav.Rd
Labels: enhancement

#177 :bug: Convert vars to char before exporting from API subprocess
  R/utils.R
Labels: bug, High Priority Request

#185 184 s2 standardize dates changes var names for date variables needed downstream
  R/utils.R
Labels: bug

#181 148 update shapefile preprocessing function for shape names
  R/utils.R
  man/process_spatial.Rd
Labels: enhancement
