Repository nish-kishore/tidypolis, pull requests merged in 2025-05, with the labels that each got.

#186 Modularizing Step 4 of preprocessing
  R/utils.R
Labels: enhancement

#200 178 add data filtering capability to preprocess cdc()
  R/init.R
  R/utils.R
  man/check_missingness.Rd
  man/create_response_vars.Rd
  man/preprocess_cdc.Rd
  man/preprocess_data.Rd
  man/remove_character_dates.Rd
  man/s1_archive_old_files.Rd
  man/s1_create_change_log.Rd
  man/s1_create_core_ready_dir.Rd
  man/s1_export_final_core_ready_files.Rd
  man/s1_get_most_recent_files.Rd
  man/s1_prep_polis_tables.Rd
  man/s2_check_duplicated_epids.Rd
  man/s2_check_missingness.Rd
  man/s2_compare_with_archive.Rd
  man/s2_export_afp_outputs.Rd
  man/s2_export_missing_onsets.Rd
  man/s2_find_latest_archive.Rd
  man/s2_fully_process_afp_data.Rd
  man/s2_process_coordinates.Rd
  man/s3_fully_process_sia_data.Rd
  man/s3_sia_check_metadata.Rd
  man/s3_sia_evaluate_unmatched_guids.Rd
  man/s3_sia_load_data.Rd
  man/s3_sia_merge_cluster_dates_final_data.Rd
  man/s3_sia_write_precluster_data.Rd
  man/s4_es_check_metadata.Rd
  man/s4_es_create_cdc_vars.Rd
  man/s4_es_data_processing.Rd
  man/s4_es_load_data.Rd
  man/s4_es_write_data.Rd
  man/s4_fully_process_es_data.Rd
  man/s5_fully_process_pos_data.Rd
  man/s5_pos_check_duplicates.Rd
  man/s5_pos_compare_with_archive.Rd
  man/s5_pos_create_cdc_vars.Rd
  man/s5_pos_load_data.Rd
  man/s5_pos_process_es_virus.Rd
  man/s5_pos_process_human_virus.Rd
  man/s5_pos_write_missing_onsets.Rd
Labels: bug, enhancement

#198 192 create a local preprocessing vignette
  vignettes/download-process-polis-data.rmd
Labels: documentation
